## Introduction
At Duke University, STA 101 is the primary introductory statistics course, 
where students are assumed to have entered the class without any statistical 
knowledge. The majority of the students enrolled in the course do not plan to 
pursue a future statistical education, which lends the course to one centered 
around the learning of statistical applications, where students are taught how 
to relate the concepts covered in STA 101 to their future works.

At the beginning, the students are split into groups where they complete 
assignments throughout the course together. The class is split into seven units,
and every section has at least one lab, taught in R, to bolster the 
learning segment. 

To conclude the semester, students display their grasp of the course through a
project conducted in R with their student group. The project, while 
constrained to a specific dataset, is relatively open-ended, as the groups can 
analyze various features of the data.

Due to the nature of flexibility promoted by this project, students are 
encouraged to display aspects of creativity in their analyses, whether it is 
focusing on solely movies produced by Warner Bros. Entertainment Inc., or
producing a new variable tracking if a movie received a nomination for best 
director, best actor or best actress. Creativity often stems from the 
exploratory data analysis process, where groups can find anomalies and/or 
interesting aspects that they can choose to further analyze as they progress to
the analysis required in the project. 

The importance of utilizing programming languages in introductory statistics 
courses is due to the inherent nature of the class. Since the majority of 
students will *apply* the concepts covered in the course in their 
future work, an effective tool is using a programming tool. The most popular
one in the scope of statistics in R, which has become widely used in the field.
When using R as a supplement to the course, there are two prevailing, and 
competing, techniques. Either students can be instructed to work with a 
relatively new suite of packages called the Tidyverse, or to use Base R commands
that have been in use for far longer. The Tidyverse was created to make
coding in R simpler, but with that comes less of an internet community due to 
its relatively young age. At the University, STA 101 classes have been taught 
distinctly using one or the other, which creates an optimal platform for 
analyzing the differences in using these syntaxes.

Does one coding technique encourage a certain level of creativity not inforced 
by the other? That is the question this study seeks to discover through the 
analysis of these group projects, which are available using both base R and 
Tidyverse methods.

Creativity can be measured by marking certain aspects of the exploratory data 
analysis process, such as tracking the mutation and creation of new variables, 
subsetting the dataset, and analyzing specific groups within the data. 

We begin by checking to ensure that needed packages are installed and then we load them into our current working environment:

```{r load_pkgs, message=FALSE}
# List of packages required for this analysis
pkg <- c("dplyr", "ggplot2", "knitr", "bookdown", "devtools")
# Check if packages are not installed and assign the
# names of the packages not installed to the variable new.pkg
new.pkg <- pkg[!(pkg %in% installed.packages())]
# If there are any packages in the list that aren't installed,
# install them
if (length(new.pkg))
  install.packages(new.pkg, repos = "http://cran.rstudio.com")
# Load packages (thesisdowndss will load all of the packages as well)
library(thesisdowndss)
```

