# Introduction

NOTES ON GAISE:

Teach statistical thinking. —students should be statistically literate after the class from a practical standpoint
a. Teach statistics as an investigative process of problem-solving and decision-making.
b. Give students experience with multivariable thinking.
	- “When students leave an introductory course, they will likely encounter situations within their own fields of study in which multiple variables relate to one another in intricate ways. We should prepare our students for challenging questions that require investigating and exploring relationships among more than two variables.”
Focus on conceptual understanding.
-	“Procedural steps too often claim students’ attention that an effective teacher could otherwise direct toward concepts.”
-	Focus on students’ understanding of key concepts, illustrated by a few techniques, rather than covering a multitude of techniques with minimal focus on underlying ideas.
-	
Integrate real data with a context and purpose.
- Make sure questions used with data sets are of interest to students so they can be easily motivated.

 Foster active learning.
Use technology to explore concepts and analyze data.
- By adopting the best available tools (subject to institutional constraints), we allow students to do analysis more easily and therefore open up time to focus on interpretation of results and testing of conditions, rather than on computational mechanics.
- Regardless of the tools used, it is important to view the use of technology not just as a way to generate statistical output but as a way to explore conceptual ideas and enhance student learning

Use assessments to improve and evaluate student learning.



At Duke University, STA 101 is the primary introductory statistics course, 
where students are assumed to have entered the class without any statistical 
knowledge. The majority of the students enrolled in the course do not plan to 
pursue a future statistical education, which lends the course to one centered 
around the learning of statistical applications, where students are taught how 
to relate the concepts covered in STA 101 to their future works.

At the beginning, the students are split into groups where they complete 
assignments throughout the course together. The class is split into seven units,
and every section has at least one lab, taught in R, to bolster the 
learning segment. 

To conclude the semester, students display their grasp of the course through a
project conducted in R with their student group. The project, while 
constrained to a specific dataset, is relatively open-ended, as the groups can 
analyze various features of the data.

Due to the nature of flexibility promoted by this project, students are 
encouraged to display aspects of creativity in their analyses, whether it is 
focusing on solely movies produced by Warner Bros. Entertainment Inc., or
producing a new variable tracking if a movie received a nomination for best 
director, best actor or best actress. Creativity often stems from the 
exploratory data analysis process, where groups can find anomalies and/or 
interesting aspects that they can choose to further analyze as they progress to
the analysis required in the project. 

The importance of utilizing programming languages in introductory statistics 
courses is due to the inherent nature of the class. Since the majority of 
students will *apply* the concepts covered in the course in their 
future work, an effective tool is using a programming tool. The most popular
one in the scope of statistics in R, which has become widely used in the field.
When using R as a supplement to the course, there are two prevailing, and 
competing, techniques. Either students can be instructed to work with a 
relatively new suite of packages called the tidyverse, or to use Base R commands
that have been in use for far longer. The tidyverse was created to make
coding in R simpler, but with that comes less of an internet community due to 
its relatively young age. At the University, STA 101 classes have been taught 
distinctly using one or the other, which creates an optimal platform for 
analyzing the differences in using these syntaxes.

Does one coding technique encourage a certain level of creativity not inforced 
by the other? That is the question this study seeks to discover through the 
analysis of these group projects, which are available using both base R and 
tidyverse methods.