# Conclusion

Due to the discrepancies in creativity, depth, and multivariate visualization 
scores between students projects using base R and others employing the tidyverse
syntax, we recommend that the tidyverse syntax should be the primary syntax when
using R as a supplement for introductory statistics courses. Although the sample
is limited by solely analyzing Duke's STA 101 final projects, the standardization
of STA 101 classes provides an optimal baseline for comparison. Another potential
source of bias, the project assignment document, can be nullified by the lack of
wording differences since the Fall 2013 document (a base R class) supplemented
by a similar creativity metric distribution for the Fall 2013 class as other
base R section. As such, since
there was shown to be higher scores in the three metrics for projects using the 
tidyverse syntax, the project language is not considered to be a confounding 
variable.

For our scoring mechanism, initially, we inputted the grades received for the 
assignment prior to coding the indicator variables. However, after the first two
classes were coded, we recognized that the grades might provide a potential source
of error, so the grades were subsequently inputted for all future projects after
the entire submission was scored. In an attempt to fully expell any bias, we 
confirmed the variable coding a second time while ignoring the grades received,
and tough scoring situations were confirmed via collaboration between Mr. Feder
and Dr. Çetinkaya-Rundel.

Since we could not find a significant confounding factor, we can attribute the 
distinctions in creativity, depth, and multivariate visualization scores to the 
R syntax. Additionally, since the final projects were randomly scored by course,
and then later checked, we are confident that there was no bias in the coding of
the indicator variables

We strongly encourage instructors to teach introductory R using the tidyverse syntax,
as well as `infer` for inference tasks, as we believe that the 
tidyverse's consistency encourages students to produce more creative and higher
quality work while tightly adhering to the GAISE. We decided to create educational
materials instead of attempting a form of modeling due to our desire to contribute
to the current introductory statistics curriculum.

## Future Work

We encourage others to build upon this analysis in a randomized controlled 
experimental setting since this study is solely retrospective. Although we have
attempted to eliminate all potential sources of bias, a randomized trial would 
remove ambiguity in a causal analysis. However, we acknowledge that there are 
limitations in performing a randomized experiment in a classroom setting due to 
the nature of student collaboration across sections and logistical issues. Perhaps
similar to the study performed by [@myint2019comparison], a randomized experiment
could be conducted through an online educational company.

There are additional aspects of the two syntaxes that we did not focus upon in 
the retrospective study. For beginning programmers, the readability differences
between the two methods are essential to learning. Therefore, we welcome 
experiments dissecting the readability of the two syntaxes for individuals with 
varying coding backgrounds.

We believe it may be important to conduct follow up studies on the same 
individuals in regards to three goals mentioned in the GAISE: tracking these 
students' motivation to learn R while in the introductory statistics class, 
subsequent performance in more advanced R or other programming topics, and 
tracking the discrepancies in retention rates within the statistics and data 
science fields. Another study could work in supplement by having the students from
this one to interpret their code after a certain amount of elapsed time to 
determine if it can still be understood.

Finally, our work assumes that `infer` will be more effective than using the
`inference()` function in teaching students inference tasks in R. However, there
have not been any studies to suggest this notion, and thus, we encourage others
to determine the differences in student learning when taught inference through 
`inference()` compared to `infer`.
