---
author: 'Benjamin Feder'
date: 'May 2019'
institution: 'Duke University'
division: 'Trinity College of Arts and Sciences'
advisor: 'Mine Çetinkaya-Rundel'
committeememberone: 'Colin Rundel'
committeemembertwo: 'Maria Tackett'
dus: 'Amy Herring'
department: 'Department of Statistical Science'
degree: 'Bachelor of Science in Statistical Science'
title: 'Evaluating Student Creativity, Depth and Multivariate Visualizations of Data Analysis projects based on R Syntax and Packages'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
#  thesisdowndss::thesis_pdf: default
  thesisdowndss::thesis_gitbook: default
#  thesisdowndss::thesis_word: default
#  thesisdowndss::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
acknowledgements: |
# dedication: |
#   You can have a dedication here if you wish.
# preface: |
#   This is an example of a thesis setup to use the reed thesis document class
#   (for LaTeX) and the R bookdown package, in general.
bibliography: bib/thesis.bib
# Refer to your specific bibliography file in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
# lot: true #TABLES
# lof: true #FIGURES
space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---
<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!
If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.
If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
library(thesisdowndss)
library(servr)
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Abstract {-}

Programming has become an essential component of introductory statistics, as 
students use R to explore general concepts. Currently, there are two methods of 
teaching R for beginning statisticians, but not much literature on how they affect
student comprehension and analysis. We analyzed 205 final projects written using
the two syntaxes for an introductory statistics course at Duke University from 
the 2013-2016 academic years, creating a variety of indicator variables to 
measure their creativity, depth and the complexity of multivariate visualizations.
Student projects using the tidyverse syntax were found to score significantly 
higher on all three metrics, suggesting instructors should employ the tidyverse 
when teaching beginning statistics. Based on these results from the retrospective
study, we created resources designed for future use in statistical instruction.

*Keywords*: Introductory statistics, Education, Tidyverse, Creativity, Depth,
Multivariate visualizations, Retrospective study

## Acknowledgements {-}

I thank my advisor, Dr. Mine Çetinkaya-Rundel for her immense dedication and 
support in supervising this project. I could not have done this without her, let
alone obtain a legitimate dataset to perform a comparative analysis. I also thank
Dr. Victoria Ellison for her essential advice, and the Department of Statistical
Science for providing me with the tools to complete this project. Most of all, 
I thank my family and friends for their love and belief in me for the past 21 years.

## Dedication {-}

I dedicate my thesis to my past students for whom I have been a teaching assistant
for their enthusiasm that gave me the motivation to complete this thesis.
